### ISSUE TITLE
Enable Supabase For Auth

### ISSUE THREAD

**Issue by iamh2o** [Daylily-Informatics/bloom#24]
... explore if it works with python.

**Comment by jdurham38** [comment]
Authentication steps - 

1. Establish working supabase to python auth. - **IN PROGRESS**
2. Create a userContext file to track user information (EMAIL, SESSION KEYS ONLY **NOT PASSWORDS**)
3. When a user signs in for the first time add their email to the udat.json
4. Allow users to enter their email for auth.
5. Allow users to sign in with Gmail.
6. Allow users to sign in with Apple.
7. Allow users to sign in with Github.

**Comment by jdurham38** [comment]
Establish working supabase to python auth. - **COMPLETED**
Create a userContext file to track user information (EMAIL, SESSION KEYS ONLY NOT PASSWORDS) - **IN PROGRESS**
When a user signs in for the first time add their email to the udat.json
Allow users to enter their email for auth.
Allow users to sign in with Gmail.
Allow users to sign in with Apple.
Allow users to sign in with Github.

**Comment by iamh2o** [comment]
confirmed working!

**Comment by jdurham38** [comment]
Happy to hear!!!
