### ISSUE TITLE
Write Moar Unit Tests!

### ISSUE THREAD

**Issue by iamh2o** [Daylily-Informatics/bloom#5]
Adam,  I've started to think about how to fold in automating operational interactions of objects that isnt such a pain to first create (though, the one full path I made has been worth it over and over).  chatGPT and I are onit, my hope is to have something a bit smarter than pytests, where some params can toggle how big/fast/wide/narrow some operation might be... or just lots of pytests

**Comment by adamtracy** [comment]
IOW, are you trying to figure out a way to generate test data without having to explicitly code up the instances and relationships themselves?

**Comment by iamh2o** [comment]
Unit tests are being developed alongside new functionality, and so far so good.  These tests are also running with the automated github actions.
